### ISSUE TITLE
Move to gitlab for finer grained review permissions

### ISSUE THREAD

**Issue by doniks** [ubports/docs.ubports.com#479]
Discussed with @Flohack74 the other day: apparently review permissions on Github are organization wide, which is kinda inconvenient in that it makes the bar to promote someone to reviewer artificially high. And the docs could really do with more reviewers.

On Gitlab it's supposed to be possible to have finer grained permissions, so it should be easier to add contributors as reviewers on docs only, rather than for the whole organisation

# Exploration
So, to explore/prepare for such a move, let me:
- [x] run through https://docs.readthedocs.io/en/stable/tutorial/index.html in my own GH account 
  - -> https://github.com/doniks/rtdtut
- [x] repeat with gitlab in my own GL account 
  - -> https://gitlab.com/doniks/rtdtut 
  - -> https://rtdtutdoniksgl.readthedocs.io/en/latest/
- [x] repeat with a gitlab fork of docs in my on GL and check that it is complete and correctly layouted 
   - -> https://gitlab.com/doniks/docs.ubports.com_gl
   - -> https://doniks-docsubportscom.readthedocs.io/en/latest/ 
   - ~~... translations don't seem to be there ... seems I need "subprojects" in rtd https://docs.readthedocs.io/en/stable/localization.html but I can't figure out how to make them~~
   - also manually set up separate projects per language in rtd, set the language, set as translation subproject, e.g. https://readthedocs.org/projects/doniks-docsubportscom-gl-de/
- [ ] finish checklist
- [ ] align with whoever is relevant @Flohack74 ? 

# TODO
- make sure we keep translated versions of the website
- make sure weblate still works
- rtd subproject ubportsicondocs -> why is this a subproject?
- do we need an announcement /  downtime warning? forum & writers TG
- check whether importing into GL with "GH access" would also take issues/PRs?! as opposed to just import "url"

# Checklists for the actual move

## move
- [ ] fork/clone/update docs into GL ubports (Import->Repo from URL, public)
- [ ] rtd: "Connect Service" GL
- [ ] add to ubports rtd, name "docs.ubports.com.gitlab" NB: dots are removed from rtd url
- [ ] settings: Admin->Advanced->build PR - on that note: currently PR's and branches are built by Jenkins - rtd can build PR's/MRs I guess that's good enough
- [ ] settings: copy from current
- [ ] make sure hostname redirects to that other new rtd page

## verify
- [ ] make a dummy PR
- [ ] make a weblate PR

## followup in new docs
- [ ] review/update documentation-contribution section as needed (GL link, Editing, MR->Pipeline->External)

## cleanup in old docs

as far as I can see closing all issues is too complicated https://docs.github.com/en/actions/managing-issues-and-pull-requests/closing-inactive-issues or uncommented (Issues -> select all -> Mark as -> closed) so I suggest no general action to close/comment on PR/Issue

- [ ] update README and about, text&link "This repository is deprecated. Go to https://gitlab.com/bladiblub for the current version"
- [ ] manually make a round through any left over open PR's and open issues. It's a small number, I can handle manually and individual decide what makes sense to carry over and help as needed 
- [ ] archive https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories
- [ ] smt todo with Jenkins?

**Comment by doniks** [comment]
The topic of moving to gitlab was just discussed in a telegram chat related to reviving the weblate setup. So, assuming there is consensus that we *do* want to do this, we can  side step all the "playground" stuff, I was toying around above and shoot directly for a proper solution, so let me close this ticket and start anew over here: 

https://github.com/ubports/docs.ubports.com/issues/628
